spring:
  datasource:
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/wepping
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: local
